//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolManagement.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tool_Scrap
    {
        public int scrap_id { get; set; }
        public string scrap_applicant { get; set; }
        public string tool_number { get; set; }
        public System.DateTime scrap_date { get; set; }
        public string scrap_reason { get; set; }
        public Nullable<int> scrap_first_trial { get; set; }
        public string first_operator { get; set; }
        public Nullable<int> scrap_second_trial { get; set; }
        public string second_operator { get; set; }
        public Nullable<int> status { get; set; }
    }
}
