//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolManagement.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tool_User
    {
        public string user_number { get; set; }
        public string password { get; set; }
        public string user_name { get; set; }
        public int user_authority { get; set; }
        public Nullable<System.DateTime> user_hiredate { get; set; }
        public string user_gender { get; set; }
        public Nullable<System.DateTime> user_age { get; set; }
        public string user_address { get; set; }
        public string user_phone { get; set; }
        public string user_picture { get; set; }
        public Nullable<int> status { get; set; }
    }
}
