//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolManagement.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tool_Borrow
    {
        public string borrow_id { get; set; }
        public string borrow_applicant { get; set; }
        public string tool_number { get; set; }
        public System.DateTime borrow_date { get; set; }
        public string borrow_line { get; set; }
        public string borrow_operator { get; set; }
    }
}
