//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolManagement.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ToolEntities : DbContext
    {
        public ToolEntities()
            : base("name=ToolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tool_Bank> tool_Bank { get; set; }
        public virtual DbSet<tool_Borrow> tool_Borrow { get; set; }
        public virtual DbSet<tool_Type> tool_Type { get; set; }
        public virtual DbSet<tool_User> tool_User { get; set; }
        public virtual DbSet<tool_Repair> tool_Repair { get; set; }
        public virtual DbSet<tool_Scrap> tool_Scrap { get; set; }
    }
}
